package com.eshop.entitiy;
// Generated Apr 10, 2019 12:46:25 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Carthasproduct generated by hbm2java
 */
@Entity
@Table(name = "carthasproduct", catalog = "eshop")
public class Carthasproduct implements java.io.Serializable {

	private Integer idCartHasProduct;
	private Cart cart;
	private Product product;
	private Integer cartHasProductQty;
	private Integer cartHasProductStatus;

	public Carthasproduct() {
	}

	public Carthasproduct(Cart cart, Product product) {
		this.cart = cart;
		this.product = product;
	}

	public Carthasproduct(Cart cart, Product product, Integer cartHasProductQty, Integer cartHasProductStatus) {
		this.cart = cart;
		this.product = product;
		this.cartHasProductQty = cartHasProductQty;
		this.cartHasProductStatus = cartHasProductStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCartHasProduct", unique = true, nullable = false)
	public Integer getIdCartHasProduct() {
		return this.idCartHasProduct;
	}

	public void setIdCartHasProduct(Integer idCartHasProduct) {
		this.idCartHasProduct = idCartHasProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cart_idCart", nullable = false)
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_idProduct", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "CartHasProductQty")
	public Integer getCartHasProductQty() {
		return this.cartHasProductQty;
	}

	public void setCartHasProductQty(Integer cartHasProductQty) {
		this.cartHasProductQty = cartHasProductQty;
	}

	@Column(name = "CartHasProductStatus")
	public Integer getCartHasProductStatus() {
		return this.cartHasProductStatus;
	}

	public void setCartHasProductStatus(Integer cartHasProductStatus) {
		this.cartHasProductStatus = cartHasProductStatus;
	}

}
