package com.eshop.entitiy;
// Generated Apr 10, 2019 12:46:25 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "eshop")
public class Cart implements java.io.Serializable {

	private Integer idCart;
	private Shop shop;
	private User user;
	private Double cartTotal;
	private Double cartStatus;
	private Set<Sale> sales = new HashSet<Sale>(0);
	private Set<Carthasproduct> carthasproducts = new HashSet<Carthasproduct>(0);

	public Cart() {
	}

	public Cart(Shop shop, User user) {
		this.shop = shop;
		this.user = user;
	}

	public Cart(Shop shop, User user, Double cartTotal, Double cartStatus, Set<Sale> sales,
			Set<Carthasproduct> carthasproducts) {
		this.shop = shop;
		this.user = user;
		this.cartTotal = cartTotal;
		this.cartStatus = cartStatus;
		this.sales = sales;
		this.carthasproducts = carthasproducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCart", unique = true, nullable = false)
	public Integer getIdCart() {
		return this.idCart;
	}

	public void setIdCart(Integer idCart) {
		this.idCart = idCart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Shop_idShop", nullable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "CartTotal", precision = 22, scale = 0)
	public Double getCartTotal() {
		return this.cartTotal;
	}

	public void setCartTotal(Double cartTotal) {
		this.cartTotal = cartTotal;
	}

	@Column(name = "CartStatus", precision = 22, scale = 0)
	public Double getCartStatus() {
		return this.cartStatus;
	}

	public void setCartStatus(Double cartStatus) {
		this.cartStatus = cartStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
	public Set<Sale> getSales() {
		return this.sales;
	}

	public void setSales(Set<Sale> sales) {
		this.sales = sales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
	public Set<Carthasproduct> getCarthasproducts() {
		return this.carthasproducts;
	}

	public void setCarthasproducts(Set<Carthasproduct> carthasproducts) {
		this.carthasproducts = carthasproducts;
	}

}
