package com.eshop.entitiy;
// Generated Mar 18, 2019 10:10:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "eshop")
public class Image implements java.io.Serializable {

	private Integer idImage;
	private Product product;
	private String imagePath;
	private Integer imageStatus;

	public Image() {
	}

	public Image(Product product) {
		this.product = product;
	}

	public Image(Product product, String imagePath, Integer imageStatus) {
		this.product = product;
		this.imagePath = imagePath;
		this.imageStatus = imageStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idImage", unique = true, nullable = false)
	public Integer getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Integer idImage) {
		this.idImage = idImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_idProduct", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "ImagePath")
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "ImageStatus")
	public Integer getImageStatus() {
		return this.imageStatus;
	}

	public void setImageStatus(Integer imageStatus) {
		this.imageStatus = imageStatus;
	}

}
