package com.eshop.entitiy;
// Generated Mar 18, 2019 10:10:47 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Maincat generated by hbm2java
 */
@Entity
@Table(name = "maincat", catalog = "eshop")
public class Maincat implements java.io.Serializable {

	private Integer idMaincat;
	private String maincatName;
	private Integer maincatStatus;
	private Set<Product> products = new HashSet<Product>(0);
	@JsonIgnore
	private Set<Subcat1> subcat1s = new HashSet<Subcat1>(0);

	public Maincat() {
	}

	public Maincat(String maincatName, Integer maincatStatus, Set<Product> products, Set<Subcat1> subcat1s) {
		this.maincatName = maincatName;
		this.maincatStatus = maincatStatus;
		this.products = products;
		this.subcat1s = subcat1s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMaincat", unique = true, nullable = false)
	public Integer getIdMaincat() {
		return this.idMaincat;
	}

	public void setIdMaincat(Integer idMaincat) {
		this.idMaincat = idMaincat;
	}

	@Column(name = "MaincatName")
	public String getMaincatName() {
		return this.maincatName;
	}

	public void setMaincatName(String maincatName) {
		this.maincatName = maincatName;
	}

	@Column(name = "MaincatStatus")
	public Integer getMaincatStatus() {
		return this.maincatStatus;
	}

	public void setMaincatStatus(Integer maincatStatus) {
		this.maincatStatus = maincatStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maincat")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maincat")
	public Set<Subcat1> getSubcat1s() {
		return this.subcat1s;
	}

	public void setSubcat1s(Set<Subcat1> subcat1s) {
		this.subcat1s = subcat1s;
	}

}
