package com.eshop.entitiy;
// Generated Apr 10, 2019 12:46:25 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name = "page", catalog = "eshop")
public class Page implements java.io.Serializable {

	private Integer idPage;
	private String url;
	private String pageName;
	private String pageCol;
	private Set<UsertypeHasPage> usertypeHasPages = new HashSet<UsertypeHasPage>(0);

	public Page() {
	}

	public Page(String url, String pageName, String pageCol, Set<UsertypeHasPage> usertypeHasPages) {
		this.url = url;
		this.pageName = pageName;
		this.pageCol = pageCol;
		this.usertypeHasPages = usertypeHasPages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPage", unique = true, nullable = false)
	public Integer getIdPage() {
		return this.idPage;
	}

	public void setIdPage(Integer idPage) {
		this.idPage = idPage;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "PageName", length = 45)
	public String getPageName() {
		return this.pageName;
	}

	public void setPageName(String pageName) {
		this.pageName = pageName;
	}

	@Column(name = "PageCol", length = 45)
	public String getPageCol() {
		return this.pageCol;
	}

	public void setPageCol(String pageCol) {
		this.pageCol = pageCol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "page")
	public Set<UsertypeHasPage> getUsertypeHasPages() {
		return this.usertypeHasPages;
	}

	public void setUsertypeHasPages(Set<UsertypeHasPage> usertypeHasPages) {
		this.usertypeHasPages = usertypeHasPages;
	}

}
