package com.eshop.entitiy;
// Generated Mar 18, 2019 10:10:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "price", catalog = "eshop")
public class Price implements java.io.Serializable {

	private Integer idPrice;
	private Product product;
	private Double buying;
	private Double minimum;
	private Double maximum;
	private Integer priceStatus;

	public Price() {
	}

	public Price(Product product) {
		this.product = product;
	}

	public Price(Product product, Double buying, Double minimum, Double maximum, Integer priceStatus) {
		this.product = product;
		this.buying = buying;
		this.minimum = minimum;
		this.maximum = maximum;
		this.priceStatus = priceStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPrice", unique = true, nullable = false)
	public Integer getIdPrice() {
		return this.idPrice;
	}

	public void setIdPrice(Integer idPrice) {
		this.idPrice = idPrice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_idProduct", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "buying", precision = 22, scale = 0)
	public Double getBuying() {
		return this.buying;
	}

	public void setBuying(Double buying) {
		this.buying = buying;
	}

	@Column(name = "minimum", precision = 22, scale = 0)
	public Double getMinimum() {
		return this.minimum;
	}

	public void setMinimum(Double minimum) {
		this.minimum = minimum;
	}

	@Column(name = "maximum", precision = 22, scale = 0)
	public Double getMaximum() {
		return this.maximum;
	}

	public void setMaximum(Double maximum) {
		this.maximum = maximum;
	}

	@Column(name = "Price_status")
	public Integer getPriceStatus() {
		return this.priceStatus;
	}

	public void setPriceStatus(Integer priceStatus) {
		this.priceStatus = priceStatus;
	}

}
