package com.eshop.entitiy;
// Generated Apr 10, 2019 12:46:25 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "price", catalog = "eshop")
public class Price implements java.io.Serializable {

	private Integer idPrice;
	private Product product;
	private Double buying;
	private Double profit;
	private Double coinval;
	private Double others;
	private Double selling;
	private Double discountRate;
	private Double discountPrice;
	private Double biforDiscount;
	private Integer priceStatus;

	public Price() {
	}

	public Price(Product product, Double buying, Double profit, Double coinval, Double others, Double selling,
			Double discountRate, Double discountPrice, Double biforDiscount, Integer priceStatus) {
		this.product = product;
		this.buying = buying;
		this.profit = profit;
		this.coinval = coinval;
		this.others = others;
		this.selling = selling;
		this.discountRate = discountRate;
		this.discountPrice = discountPrice;
		this.biforDiscount = biforDiscount;
		this.priceStatus = priceStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPrice", unique = true, nullable = false)
	public Integer getIdPrice() {
		return this.idPrice;
	}

	public void setIdPrice(Integer idPrice) {
		this.idPrice = idPrice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_idProduct")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "buying", precision = 22, scale = 0)
	public Double getBuying() {
		return this.buying;
	}

	public void setBuying(Double buying) {
		this.buying = buying;
	}

	@Column(name = "profit", precision = 22, scale = 0)
	public Double getProfit() {
		return this.profit;
	}

	public void setProfit(Double profit) {
		this.profit = profit;
	}

	@Column(name = "coinval", precision = 22, scale = 0)
	public Double getCoinval() {
		return this.coinval;
	}

	public void setCoinval(Double coinval) {
		this.coinval = coinval;
	}

	@Column(name = "others", precision = 22, scale = 0)
	public Double getOthers() {
		return this.others;
	}

	public void setOthers(Double others) {
		this.others = others;
	}

	@Column(name = "selling", precision = 22, scale = 0)
	public Double getSelling() {
		return this.selling;
	}

	public void setSelling(Double selling) {
		this.selling = selling;
	}

	@Column(name = "discount_rate", precision = 22, scale = 0)
	public Double getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(Double discountRate) {
		this.discountRate = discountRate;
	}

	@Column(name = "discount_price", precision = 22, scale = 0)
	public Double getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(Double discountPrice) {
		this.discountPrice = discountPrice;
	}

	@Column(name = "bifor_discount", precision = 22, scale = 0)
	public Double getBiforDiscount() {
		return this.biforDiscount;
	}

	public void setBiforDiscount(Double biforDiscount) {
		this.biforDiscount = biforDiscount;
	}

	@Column(name = "price_status")
	public Integer getPriceStatus() {
		return this.priceStatus;
	}

	public void setPriceStatus(Integer priceStatus) {
		this.priceStatus = priceStatus;
	}

}
