package com.eshop.entitiy;
// Generated Apr 10, 2019 12:46:25 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "eshop")
public class Product implements java.io.Serializable {

	private Integer idProduct;
	private Maincat maincat;
	private Subcat1 subcat1;
	private Subcat2 subcat2;
	private User user;
	private String productName;
	private String productCode;
	private String productVolume;
	private String productDescription;
	private String productFb;
	private String productComment;
	private String productcol1;
	private String productcol2;
	private String productcol3;
	private Integer productGender;
	private Integer productStatus1;
	private Integer productStatus2;
	private String productDescriptionEng;
	private Set<Rating> ratings = new HashSet<Rating>(0);
	private Set<Image> images = new HashSet<Image>(0);
	private Set<Carthasproduct> carthasproducts = new HashSet<Carthasproduct>(0);
	private Set<Price> prices = new HashSet<Price>(0);

	public Product() {
	}

	public Product(Maincat maincat, Subcat1 subcat1, Subcat2 subcat2) {
		this.maincat = maincat;
		this.subcat1 = subcat1;
		this.subcat2 = subcat2;
	}

	public Product(Maincat maincat, Subcat1 subcat1, Subcat2 subcat2, User user, String productName, String productCode,
			String productVolume, String productDescription, String productFb, String productComment,
			String productcol1, String productcol2, String productcol3, Integer productGender, Integer productStatus1,
			Integer productStatus2, String productDescriptionEng, Set<Rating> ratings, Set<Image> images,
			Set<Carthasproduct> carthasproducts, Set<Price> prices) {
		this.maincat = maincat;
		this.subcat1 = subcat1;
		this.subcat2 = subcat2;
		this.user = user;
		this.productName = productName;
		this.productCode = productCode;
		this.productVolume = productVolume;
		this.productDescription = productDescription;
		this.productFb = productFb;
		this.productComment = productComment;
		this.productcol1 = productcol1;
		this.productcol2 = productcol2;
		this.productcol3 = productcol3;
		this.productGender = productGender;
		this.productStatus1 = productStatus1;
		this.productStatus2 = productStatus2;
		this.productDescriptionEng = productDescriptionEng;
		this.ratings = ratings;
		this.images = images;
		this.carthasproducts = carthasproducts;
		this.prices = prices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idProduct", unique = true, nullable = false)
	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Maincat_idMaincat", nullable = false)
	public Maincat getMaincat() {
		return this.maincat;
	}

	public void setMaincat(Maincat maincat) {
		this.maincat = maincat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Subcat1_idSubcat1", nullable = false)
	public Subcat1 getSubcat1() {
		return this.subcat1;
	}

	public void setSubcat1(Subcat1 subcat1) {
		this.subcat1 = subcat1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Subcat2_idSubcat2", nullable = false)
	public Subcat2 getSubcat2() {
		return this.subcat2;
	}

	public void setSubcat2(Subcat2 subcat2) {
		this.subcat2 = subcat2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_idUser")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "ProductName")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "ProductCode", length = 45)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "ProductVolume", length = 45)
	public String getProductVolume() {
		return this.productVolume;
	}

	public void setProductVolume(String productVolume) {
		this.productVolume = productVolume;
	}

	@Column(name = "ProductDescription")
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@Column(name = "ProductFb", length = 65535)
	public String getProductFb() {
		return this.productFb;
	}

	public void setProductFb(String productFb) {
		this.productFb = productFb;
	}

	@Column(name = "ProductComment", length = 65535)
	public String getProductComment() {
		return this.productComment;
	}

	public void setProductComment(String productComment) {
		this.productComment = productComment;
	}

	@Column(name = "Productcol1", length = 45)
	public String getProductcol1() {
		return this.productcol1;
	}

	public void setProductcol1(String productcol1) {
		this.productcol1 = productcol1;
	}

	@Column(name = "Productcol2", length = 45)
	public String getProductcol2() {
		return this.productcol2;
	}

	public void setProductcol2(String productcol2) {
		this.productcol2 = productcol2;
	}

	@Column(name = "Productcol3", length = 45)
	public String getProductcol3() {
		return this.productcol3;
	}

	public void setProductcol3(String productcol3) {
		this.productcol3 = productcol3;
	}

	@Column(name = "ProductGender")
	public Integer getProductGender() {
		return this.productGender;
	}

	public void setProductGender(Integer productGender) {
		this.productGender = productGender;
	}

	@Column(name = "ProductStatus1")
	public Integer getProductStatus1() {
		return this.productStatus1;
	}

	public void setProductStatus1(Integer productStatus1) {
		this.productStatus1 = productStatus1;
	}

	@Column(name = "ProductStatus2")
	public Integer getProductStatus2() {
		return this.productStatus2;
	}

	public void setProductStatus2(Integer productStatus2) {
		this.productStatus2 = productStatus2;
	}

	@Column(name = "ProductDescriptionEng")
	public String getProductDescriptionEng() {
		return this.productDescriptionEng;
	}

	public void setProductDescriptionEng(String productDescriptionEng) {
		this.productDescriptionEng = productDescriptionEng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Rating> getRatings() {
		return this.ratings;
	}

	public void setRatings(Set<Rating> ratings) {
		this.ratings = ratings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Carthasproduct> getCarthasproducts() {
		return this.carthasproducts;
	}

	public void setCarthasproducts(Set<Carthasproduct> carthasproducts) {
		this.carthasproducts = carthasproducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Price> getPrices() {
		return this.prices;
	}

	public void setPrices(Set<Price> prices) {
		this.prices = prices;
	}

}
