package com.eshop.entitiy;
// Generated Mar 18, 2019 10:10:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "rating", catalog = "eshop")
public class Rating implements java.io.Serializable {

	private Integer idRating;
	private Product product;
	private Double ratingNumber;
	private String ratingComment;
	private String ratingUserName;
	private Integer ratingUserId;

	public Rating() {
	}

	public Rating(Product product) {
		this.product = product;
	}

	public Rating(Product product, Double ratingNumber, String ratingComment, String ratingUserName,
			Integer ratingUserId) {
		this.product = product;
		this.ratingNumber = ratingNumber;
		this.ratingComment = ratingComment;
		this.ratingUserName = ratingUserName;
		this.ratingUserId = ratingUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idRating", unique = true, nullable = false)
	public Integer getIdRating() {
		return this.idRating;
	}

	public void setIdRating(Integer idRating) {
		this.idRating = idRating;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_idProduct", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "RatingNumber", precision = 22, scale = 0)
	public Double getRatingNumber() {
		return this.ratingNumber;
	}

	public void setRatingNumber(Double ratingNumber) {
		this.ratingNumber = ratingNumber;
	}

	@Column(name = "RatingComment", length = 65535)
	public String getRatingComment() {
		return this.ratingComment;
	}

	public void setRatingComment(String ratingComment) {
		this.ratingComment = ratingComment;
	}

	@Column(name = "RatingUserName")
	public String getRatingUserName() {
		return this.ratingUserName;
	}

	public void setRatingUserName(String ratingUserName) {
		this.ratingUserName = ratingUserName;
	}

	@Column(name = "RatingUserId")
	public Integer getRatingUserId() {
		return this.ratingUserId;
	}

	public void setRatingUserId(Integer ratingUserId) {
		this.ratingUserId = ratingUserId;
	}

}
