package com.eshop.entitiy;
// Generated Mar 18, 2019 10:10:47 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shophasproduct generated by hbm2java
 */
@Entity
@Table(name = "shophasproduct", catalog = "eshop")
public class Shophasproduct implements java.io.Serializable {

	private Integer idShopHasProduct;
	private Shop shop;
	private Integer productIdProduct;
	private Date addDate;
	private Date removeDate;
	private Integer shopHasProductStatus;

	public Shophasproduct() {
	}

	public Shophasproduct(Shop shop) {
		this.shop = shop;
	}

	public Shophasproduct(Shop shop, Integer productIdProduct, Date addDate, Date removeDate,
			Integer shopHasProductStatus) {
		this.shop = shop;
		this.productIdProduct = productIdProduct;
		this.addDate = addDate;
		this.removeDate = removeDate;
		this.shopHasProductStatus = shopHasProductStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idShopHasProduct", unique = true, nullable = false)
	public Integer getIdShopHasProduct() {
		return this.idShopHasProduct;
	}

	public void setIdShopHasProduct(Integer idShopHasProduct) {
		this.idShopHasProduct = idShopHasProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Shop_idShop", nullable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@Column(name = "Product_idProduct")
	public Integer getProductIdProduct() {
		return this.productIdProduct;
	}

	public void setProductIdProduct(Integer productIdProduct) {
		this.productIdProduct = productIdProduct;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "addDate", length = 26)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "removeDate", length = 26)
	public Date getRemoveDate() {
		return this.removeDate;
	}

	public void setRemoveDate(Date removeDate) {
		this.removeDate = removeDate;
	}

	@Column(name = "ShopHasProductStatus")
	public Integer getShopHasProductStatus() {
		return this.shopHasProductStatus;
	}

	public void setShopHasProductStatus(Integer shopHasProductStatus) {
		this.shopHasProductStatus = shopHasProductStatus;
	}

}
