package com.eshop.entitiy;
// Generated Apr 10, 2019 12:46:25 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Statusdata generated by hbm2java
 */
@Entity
@Table(name = "statusdata", catalog = "eshop")
public class Statusdata implements java.io.Serializable {

	private Integer idStatusData;
	private Integer statusNumber;
	private String statusDiscriition;

	public Statusdata() {
	}

	public Statusdata(Integer statusNumber, String statusDiscriition) {
		this.statusNumber = statusNumber;
		this.statusDiscriition = statusDiscriition;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idStatusData", unique = true, nullable = false)
	public Integer getIdStatusData() {
		return this.idStatusData;
	}

	public void setIdStatusData(Integer idStatusData) {
		this.idStatusData = idStatusData;
	}

	@Column(name = "StatusNumber")
	public Integer getStatusNumber() {
		return this.statusNumber;
	}

	public void setStatusNumber(Integer statusNumber) {
		this.statusNumber = statusNumber;
	}

	@Column(name = "StatusDiscriition", length = 45)
	public String getStatusDiscriition() {
		return this.statusDiscriition;
	}

	public void setStatusDiscriition(String statusDiscriition) {
		this.statusDiscriition = statusDiscriition;
	}

}
