package com.eshop.entitiy;
// Generated Mar 18, 2019 10:10:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsertypeHasPage generated by hbm2java
 */
@Entity
@Table(name = "usertype_has_page", catalog = "eshop")
public class UsertypeHasPage implements java.io.Serializable {

	private Integer userTypeHasPagecol;
	private Page page;
	private Usertype usertype;

	public UsertypeHasPage() {
	}

	public UsertypeHasPage(Page page, Usertype usertype) {
		this.page = page;
		this.usertype = usertype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserType_has_Pagecol", unique = true, nullable = false)
	public Integer getUserTypeHasPagecol() {
		return this.userTypeHasPagecol;
	}

	public void setUserTypeHasPagecol(Integer userTypeHasPagecol) {
		this.userTypeHasPagecol = userTypeHasPagecol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Page_idPage", nullable = false)
	public Page getPage() {
		return this.page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserType_idUserType", nullable = false)
	public Usertype getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Usertype usertype) {
		this.usertype = usertype;
	}

}
